CATEGORY_FILTERS = {
    "Gender": {
      "Female": "1001",
      "Male": "1002",
      "Non-Binary": "1712"
    },
    "Session Type": {
      "In Person": "1995",
      "Online": "595",
    },
    "Specialties": {
      "Addiction": "4",
      "ADHD": "6",
      "Adoption": "180",
      "Alcohol Use": "248",
      "Anger Management": "166",
      "Anxiety": "3",
      "Autism": "167",
      "Behavioural Issues": "195",
      "Bipolar Disorder": "168",
      "Body Positivity": "1703",
      "Borderline Personality (BPD)": "196",
      "Cancer": "267",
      "Career Guidance": "183",
      "Child": "5",
      "Chronic Illness": "636",
      "Chronic Pain": "7",
      "Codependency": "503",
      "Dementia": "193",
      "Depression": "2",
      "Dissociative Disorders (DID)": "20",
      "Divorce": "26",
      "Domestic Abuse": "8",
      "Drug Abuse": "253",
      "Dual Diagnosis": "263",
      "Eating Disorders": "9",
      "Education and Learning Disabilities": "184",
      "First Responders": "1997",
      "Gambling": "254",
      "Geriatric and Seniors": "10",
      "Grief": "14",
      "Hoarding": "646",
      "Infertility": "12",
      "Infidelity": "551",
      "Intellectual Disability": "264",
      "Internet Addiction": "202",
      "Life Coaching": "13",
      "Marriage Counselling": "1200",
      "Medical Detox": "259",
      "Medication Management": "258",
      "Men's Issues": "576",
      "Narcissistic Personality (NPD)": "203",
      "Obesity": "255",
      "Obsessive-Compulsive (OCD)": "15",
      "Open Relationships Non-Monogamy": "1704",
      "Oppositional Defiance (ODD)": "204",
      "Parenting": "16",
      "Personality Disorders": "22",
      "Pregnancy, Prenatal, Postpartum": "578",
      "Psychosis": "23",
      "Racial Identity": "584",
      "Relationship Issues": "1",
      "Self Esteem": "260",
      "Self-Harming": "283",
      "Sex Therapy": "17",
      "Sex-Positive, Kink Allied": "1705",
      "Sexual Abuse": "256",
      "Sexual Addiction": "257",
      "Sleep or Insomnia": "190",
      "Spirituality": "18",
      "Sports Performance": "597",
      "Stress": "632",
      "Substance Use": "182",
      "Suicidal Ideation": "205",
      "Testing and Evaluation": "177",
      "Transgender": "187",
      "Trauma and PTSD": "19",
      "Traumatic Brain Injury (TBI)": "206",
      "Veterans": "510",
      "Video Game Addiction": "207",
      "Weight Loss": "262",
      "Women's Issues": "575"
    },
    "Insurance": {
      "Aetna": "415",
      "Alberta Blue Cross": "1934",
      "Alliance": "416",
      "Arete": "1939",
      "ASEBP | Alberta School Employee": "1947",
      "Blue Cross": "590",
      "Blue Shield": "592",
      "BlueCross BlueShield": "423",
      "Canada Life | Great-West Life": "1937",
      "Chambers of Commerce": "1988",
      "CINUP": "1989",
      "ComPsych": "431",
      "Crime Victim (CVAP / VQRP / IVAC)": "1940",
      "Desjardins": "1935",
      "Empire Blue Cross Blue Shield": "513",
      "Equitable Life of Canada": "1933",
      "First Canadian Health": "1946",
      "First Choice Health | FCH": "434",
      "Great-West Life": "437",
      "Green Shield Canada": "561",
      "Guardian": "438",
      "Health Net": "440",
      "Homewood Health": "1824",
      "Humana": "445",
      "iA Financial | Industrial Alliance": "1949",
      "Insurance Corporation of British Columbia": "1823",
      "Johnson Health Plan": "1991",
      "Johnston Group": "1987",
      "LifeWise": "449",
      "Manulife": "642",
      "Maximum Benefit": "1990",
      "Medavie Blue Cross": "1826",
      "Medicare": "456",
      "Meridian": "549",
      "Military OneSource": "526",
      "MultiPlan": "458",
      "Non-Insured Health | First Nations": "1932",
      "Pacific Blue Cross": "638",
      "RCMP | Royal Canadian Mounted Police": "1950",
      "Sentara Health Plans": "543",
      "SunLife": "640",
      "TELUS Health": "1822",
      "The Co-operators": "1943",
      "UHC UnitedHealthcare UBH United Behavioral Health": "473",
      "Veterans Affairs Canada (VAC)": "1948",
      "WSIB | Workplace Safety Insurance Board": "1938"
    },
    "Types of Therapy": {
      "Acceptance and Commitment": "580",
      "Adlerian": "620",
      "AEDP": "1657",
      "Applied Behavioural Analysis": "622",
      "Art Therapy": "489",
      "Attachment-based": "496",
      "Biofeedback": "648",
      "Brainspotting": "1652",
      "Christian Counselling": "637",
      "Clinical Supervision and Qualified Supervisors": "656",
      "Coaching": "294",
      "Cognitive Behavioural": "293",
      "Cognitive Processing": "1850",
      "Compassion Focused": "654",
      "Couples Counselling": "1201",
      "Culturally Sensitive": "582",
      "Dance Movement Therapy": "1634",
      "Dialectical Behavior": "488",
      "Eclectic": "295",
      "EMDR": "301",
      "Emotionally Focused": "491",
      "Energy Psychology": "1861",
      "Existential": "310",
      "Experiential Therapy": "618",
      "Exposure Response Prevention": "1856",
      "Expressive Arts": "499",
      "Family Systems": "311",
      "Family Therapy": "1203",
      "Feminist": "588",
      "Forensic Psychology": "302",
      "Gestalt": "309",
      "Gottman Method": "511",
      "Humanistic": "297",
      "Hypnotherapy": "305",
      "Imago": "493",
      "Integrative": "498",
      "Internal Family Systems": "608",
      "Interpersonal": "306",
      "Intervention": "313",
      "Jungian": "497",
      "Mindfulness-Based": "307",
      "Motivational Interviewing": "492",
      "Multicultural": "586",
      "Music Therapy": "1857",
      "Narrative": "490",
      "Neuro-Linguistic": "502",
      "Neurofeedback": "501",
      "Parent-Child Interaction": "610",
      "Person-Centered": "628",
      "Play Therapy": "312",
      "Positive Psychology": "612",
      "Prolonged Exposure Therapy": "624",
      "Psychoanalytic": "298",
      "Psychobiological Approach Couple Therapy": "1655",
      "Psychodynamic": "299",
      "Psychological Testing and Evaluation": "303",
      "Rational Emotive Behaviour": "614",
      "Reality Therapy": "616",
      "Relational": "308",
      "Sandplay": "500",
      "Schema Therapy": "1849",
      "Solution Focused Brief": "304",
      "Somatic": "494",
      "Strength-Based": "630",
      "Structural Family Therapy": "626",
      "Transpersonal": "300",
      "Trauma Focused": "495"
    },
    "Age": {
      "Toddler": "329",
      "Children (6 to 10)": "325",
      "Preteen": "330",
      "Teen": "326",
      "Adults": "327",
      "Elders (65+)": "328"
    },
    "Ethnicity": {
      "Asian": "335",
      "Black": "334",
      "Indigenous Peoples": "337",
      "Hispanic and Latino": "336",
      "Pacific Islander": "338"
    },
    "Sexuality": {
      "Bisexual": "185",
      "Lesbian": "186",
      "LGBTQ+": "172"
    },
    "Language": {
      "Arabic": "341",
      "Armenian": "364",
      "Bosnian": "359",
      "Cantonese": "342",
      "Croatian": "360",
      "Farsi": "366",
      "Filipino": "354",
      "French": "344",
      "German": "345",
      "Greek": "355",
      "Gujarati": "365",
      "Haitian Creole": "1848",
      "Hebrew": "346",
      "Hindi": "347",
      "Hungarian": "579",
      "Italian": "348",
      "Japanese": "356",
      "Korean": "357",
      "Mandarin": "343",
      "Polish": "367",
      "Portuguese": "349",
      "Punjabi": "350",
      "Romanian": "369",
      "Russian": "351",
      "Serbian": "361",
      "Sign Language (ASL)": "340",
      "Sinhalese": "352",
      "Spanish": "353",
      "Tamil": "1733",
      "Turkish": "372",
      "Ukrainian": "368",
      "Urdu": "370",
      "Vietnamese": "363"
    },
    "Faith": {
      "Buddhist": "404",
      "Christian": "405",
      "Hindu": "598",
      "Jewish": "407",
      "Muslim": "406",
      "Secular and Non-Religious": "1970",
      "Sikh": "1876",
      "The Church of Jesus Christ of Latter-day Saints": "408"
    },
}


'''
    "Price": {
        "$ (Less than $105)": "1",
        "$$ ($105 - $136)": "2",
        "$$$ (More than $136)": "3"
    }
'''